// Icon registry: maps a stored string key → a react-icons component.
// The admin picks a key from the searchable IconPicker; the public cards
// render it. To add more, import the icon and add a line to ICON_MAP.
import {
  FaShopify,
  FaBullhorn,
  FaLaptopCode,
  FaHandshake,
  FaBuilding,
  FaKeyboard,
  FaGraduationCap,
  FaChartLine,
  FaMobileAlt,
  FaGlobe,
  FaPenNib,
  FaUsers,
  FaCode,
  FaRegLightbulb,
  FaYoutube,
  FaAmazon,
  FaFacebook,
  FaInstagram,
  FaGoogle,
  FaPalette,
  FaCamera,
  FaVideo,
  FaComments,
  FaBriefcase,
  FaBook,
  FaLanguage,
  FaCalculator,
  FaDatabase,
  FaServer,
  FaCloud,
  FaLock,
  FaSearch,
  FaEnvelope,
  FaPhone,
  FaHeadset,
  FaRocket,
  FaCogs,
  FaDollarSign,
  FaShoppingCart,
  FaStore,
  FaChalkboardTeacher,
  FaUserTie,
  FaWordpress,
  FaReact,
  FaNodeJs,
  FaPython,
  FaHtml5,
  FaCss3Alt,
  FaJs,
} from "react-icons/fa";
import {
  MdStoreMallDirectory,
  MdLanguage,
  MdDesignServices,
  MdOndemandVideo,
  MdCampaign,
  MdComputer,
} from "react-icons/md";

export const ICON_MAP = {
  shopify: FaShopify,
  store: MdStoreMallDirectory,
  storefront: FaStore,
  marketing: FaBullhorn,
  campaign: MdCampaign,
  building: FaBuilding,
  code: FaLaptopCode,
  dev: FaCode,
  handshake: FaHandshake,
  keyboard: FaKeyboard,
  language: MdLanguage,
  englishlanguage: FaLanguage,
  graduation: FaGraduationCap,
  teacher: FaChalkboardTeacher,
  chart: FaChartLine,
  mobile: FaMobileAlt,
  globe: FaGlobe,
  design: FaPenNib,
  designservices: MdDesignServices,
  palette: FaPalette,
  users: FaUsers,
  usertie: FaUserTie,
  idea: FaRegLightbulb,
  youtube: FaYoutube,
  video: FaVideo,
  ondemandvideo: MdOndemandVideo,
  amazon: FaAmazon,
  facebook: FaFacebook,
  instagram: FaInstagram,
  google: FaGoogle,
  camera: FaCamera,
  comments: FaComments,
  briefcase: FaBriefcase,
  book: FaBook,
  calculator: FaCalculator,
  computer: MdComputer,
  database: FaDatabase,
  server: FaServer,
  cloud: FaCloud,
  lock: FaLock,
  seo: FaSearch,
  email: FaEnvelope,
  phone: FaPhone,
  headset: FaHeadset,
  rocket: FaRocket,
  settings: FaCogs,
  dollar: FaDollarSign,
  cart: FaShoppingCart,
  wordpress: FaWordpress,
  react: FaReact,
  nodejs: FaNodeJs,
  python: FaPython,
  html: FaHtml5,
  css: FaCss3Alt,
  javascript: FaJs,
};

// For the icon picker.
export const ICON_OPTIONS = Object.keys(ICON_MAP);

/** Get the icon component for a key, or null if unknown/empty. */
export function getIcon(key) {
  return ICON_MAP[key] || null;
}
